### PR TITLE
GPC-NONE: Add 0 reserved concurrent executions

### PR DESCRIPTION
**Pull request by oskarwilliams**

### CODE REVIEW

**Comment by ethanmills** [comment]
What's this for?

**Comment by ethanmills** [comment]
This can be set globally and overridden if needed https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html

**Comment by ethanmills** [comment]
Doesn't reserved concurrency of zero mean the function can never run? Or does 0 have a special meaning?

**Comment by oskarwilliams** [comment]
Ahh yes, I was treating reserved concurrency as the prewarmed amount which is wrong, I need to think of a better value for this

**Pull request closed without merging**
